---
title: unknown
date: ~
---

# eml


## dataset


### alternateIdentifier
0101d74b-afc2-3b0f-817c-dc350d2a6fe4


### alternateIdentifier
10.15468/14jd9g


### alternateIdentifier
0645ccdb-e001-4ab0-9729-51f1755e007e


### alternateIdentifier
https://collections.ala.org.au/public/show/dr368


### title
NSW BioNet Atlas


### creator


#### organizationName
Department of Planning, Industry and Environment representing the State of New South Wales


#### address


### metadataProvider


#### organizationName
Department of Planning, Industry and Environment representing the State of New South Wales


#### address


### associatedParty


#### organizationName
Atlas of Living Australia


#### address


##### deliveryPoint
CSIRO Ecosystems Services


##### city
Canberra


##### administrativeArea
ACT


##### postalCode
2601


##### country
Australia


#### electronicMailAddress
info@ala.org.au


#### role
distributor


### associatedParty


#### organizationName
Office of Environment & Heritage


#### address


#### role
originator


### pubDate
2023-04-27


### language
English


### abstract


#### para
Records from DPIE's NSW BioNet Atlas database of flora and fauna sightings. Includes records from other custodians such as the National Herbarium of NSW, Forests NSW, Australian Bird and Bat Banding Scheme and the Australian Museum.


### intellectualRights


#### para
BioNet Species Sightings occurrence data held by the NSW Office of Environment and Heritage (OEH).   The BioNet repository holds data from a number of sources and custodians. (Accessed through ALA Data Portal,<Date of Access>). 
        


#### para


##### ulink


###### citetitle
Creative Commons Attribution (International) (CC-BY 4.0 (Int) 4.0)


#### para
 
        


##### ulink


###### citetitle
Creative Commons Attribution (International) (CC-BY 4.0 (Int) 4.x)


#### para

      


### distribution


#### online


##### url
https://collections.ala.org.au/public/show/dr368


### coverage


### purpose


#### para


### contact


#### organizationName
Atlas of Living Australia


#### address


##### deliveryPoint
CSIRO Ecosystems Services


##### city
Canberra


##### administrativeArea
ACT


##### postalCode
2601


##### country
Australia


#### electronicMailAddress
info@ala.org.au


### methods


## additionalMetadata


### metadata


#### gbif


##### dateStamp
2023-04-27T01:00:07


##### hierarchyLevel
dataset


##### citation
BioNet Species Sightings occurrence data held by the NSW Office of Environment and Heritage (OEH).   The BioNet repository holds data from a number of sources and custodians. (Accessed through ALA Data Portal,<Date of Access>).


##### rights


